import apartmentImg1 from '../assets/images/apartment-1.png';
import apartmentImg2 from '../assets/images/apartment-2.png';
import apartmentImg3 from '../assets/images/apartment-3.png';
import apartmentImg4 from '../assets/images/apartment-4.png';
import apartmentImg5 from '../assets/images/apartment-5.png';
import apartmentImg6 from '../assets/images/apartment-6.png';
import apartmentImg7 from '../assets/images/apartment-7.png';
import apartmentImg8 from '../assets/images/apartment-8.png';
import apartmentImg9 from '../assets/images/apartment-9.png';

import srvLog1 from "../assets/icon/srvlogo1.png";
import srvLog2 from "../assets/icon/srvlogo2.png";
import srvLog3 from "../assets/icon/srvlogo3.png";
// import apartmentImg10 from '../assets/images/apartment-10.png';

const apartmentData = [
  {
    id: 1,
    name: "Washington Avenue",
    img: apartmentImg1,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    room: 3,
    bathrooms: 1,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 2,
    name: "Washington Avenue",
    img: apartmentImg2,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 3,
    name: "Washington Avenue",
    img: apartmentImg3,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 4,
    name: "Washington Avenue",
    img: apartmentImg4,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 5,
    name: "Washington Avenue",
    img: apartmentImg5,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 6,
    name: "Washington Avenue",
    img: apartmentImg6,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 7,
    name: "Washington Avenue",
    img: apartmentImg7,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 8,
    name: "Washington Avenue",
    img: apartmentImg8,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  {
    id: 9,
    name: "Washington Avenue",
    img: apartmentImg9,
    area: "54m",
    location: "Nsirabad H/s, Chattogram",
    bathrooms: 1,
    room: 3,
    parkingPlaces: 2,
    price: 600,
    service: [
      "Air Condition",
      "Internet",
      "Cable - Tv",
      "Balcony",
      "Garage",
      "Lift",
      "High standard",
      "City Center",
    ],
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  },
  // {
  //   id: 10,
  //   name: "Washington Avenue",
  //   img: apartmentImg10,
  //   area: "54m",
  //   location: "Nsirabad H/s, Chattogram",
  //   bathrooms: 1,
  //   room: 3,
  //   parkingPlaces: 2,
  //   price: 600,
  //   service: [
  //     "Air Condition",
  //     "Internet",
  //     "Cable - Tv",
  //     "Balcony",
  //     "Garage",
  //     "Lift",
  //     "High standard",
  //     "City Center",
  //   ],
  //   details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit at nobis saepe, natus nisi beatae",
  // },
];
const services = [
  {
    id: 1,
    name: "Wide Range of Properties",
    logo: srvLog1,
    details:
      "With a robust selection of popular properties on hand, as well as leading properties from experts.",
  },
  {
    id: 2,
    name: "Financing Made Easy",
    logo: srvLog2,
    details:
      "Our stress-free finance department that can find financial solutions to save you money.",
  },
  {
    id: 3,
    name: "Trusted by Thousands",
    logo: srvLog3,
    details:
      "10 new offers every day. 350 offers on site, trusted by a community of thousands of users.",
  },
];
export { apartmentData, services };
